### ISSUE TITLE
remove nav walker

### ISSUE THREAD

**Issue by kjsampat** [webmakersteve/generator-gulp-underscores#2]
Thanks for all your hard work! As a team we plan to use  gulp underscores for our projects moving forward. However we would like to remove the nav walker from the process. Currently commenting out the walker function (or require in functions.php) breaks the rest of the page. Do you have a suggestion on how to do this?

**Comment by webmakersteve** [comment]
If you comment out the walker you will also need to edit the template function to not specify a walker. 

https://github.com/webmakersteve/generator-gulp-underscores/blob/e4c70f063d5b953258d4f4e4a8d984c00c90c156/generators/app/templates/_/inc/template-tags.php#L111

The file will be templated, so the function name will be different, but make sure to remove the walker key and also the fallback specification.

**Comment by kjsampat** [comment]
thanks worked great.
